services:
  - type: web
    name: earphones_review
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: earphone_review-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: earphone_review_DB
    databaseName: earphone_review_db
    user: earphones_review